language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
#  - "pip install coveralls"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then nosetests -v -c nose.cfg; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then green -v; fi
# after_success: coveralls
