#!/usr/bin/perl

$value = $ARGV[0];

@units = qw/b Kb Mb Gb Tb Pb Eb/;

$unit = shift(@units);
for ($try = $value ; 1024 <= $try ; $try /= 1024)
{
   $unit = shift(@units);
}

printf("%s = %3.2f %s\n", $value, $try, $unit);

__END__

=head1 NAME

magnitude - report the size of a number

=head1 DESCRIPTION

magnitude <number>

Report the magnitude of <number>.

=head1 LICENSE

Copyright (C) 1995 - <the end of time>  Tom Barron
  tom.barron@comcast.net
  177 Crossroads Blvd
  Oak Ridge, TN  37830

This software is licensed under the CC-GNU GPL. For the full text of
the license, see http://creativecommons.org/licenses/GPL/2.0/

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

=cut

