#!/usr/bin/env python
import glob
import os
import pdb
import sys

pdb.set_trace()
ghdir = os.path.dirname(os.path.abspath(sys.argv[0]))
r = os.path.dirname(ghdir)
if not os.path.isdir(os.path.join(r, ".git")):
    raise StandardError("%s does not seem to be a git repo" % r)

td = os.path.join(r, ".git/hooks")

for fn in glob.glob("%s/*" % ghdir):
    if "mklinks" in fn or fn.endswith("~"):
        continue
    src = os.path.join(td, os.path.basename(fn))
    os.symlink(fn, src)
